name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          # See comment comes from https://github.com/ruby/setup-ruby#matrix-of-ruby-versions
          - '3.3'
          - '3.4'
          - '4.0'
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "Tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@5126516654c75f76bca1de45dd82a3006d8890f9
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: bundle exec rspec
