name: Publish Gem

on:
  push:
    branches:
      - "main"
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: discourse/publish-rubygems-action@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
